In [1]:
import torch

In [35]:
x = torch.rand(2,2,3,dtype=torch.double)
x2 = torch.tensor([2.5,1.2])
print(x2)
print(x)
print(x.dtype)
print(x.size())

tensor([2.5000, 1.2000])
tensor([[[0.2516, 0.4889, 0.0473],
         [0.2182, 0.1830, 0.4051]],

        [[0.7855, 0.1138, 0.9822],
         [0.3598, 0.2331, 0.4023]]], dtype=torch.float64)
torch.float64
torch.Size([2, 2, 3])


In [36]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x  + y
print(z)

tensor([[0.5935, 0.6900],
        [0.5808, 0.1651]])
tensor([[0.1089, 0.1391],
        [0.3906, 0.2120]])
tensor([[0.7025, 0.8291],
        [0.9714, 0.3770]])


In [37]:
y.add_(x) #In place addition
print(y)

tensor([[0.7025, 0.8291],
        [0.9714, 0.3770]])


In [46]:
x = torch.rand(5,3)
print(x)
print(x[0,:])
print(x[1,1].item())

tensor([[0.1351, 0.6766, 0.7949],
        [0.7097, 0.5933, 0.7128],
        [0.8965, 0.0035, 0.7622],
        [0.3372, 0.9161, 0.1155],
        [0.7009, 0.8855, 0.4258]])
tensor([0.1351, 0.6766, 0.7949])
0.593332827091217


In [54]:
x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y.size())

tensor([[0.7426, 0.4576, 0.7567, 0.1009],
        [0.1687, 0.9380, 0.6900, 0.2601],
        [0.4079, 0.5200, 0.5888, 0.5197],
        [0.3071, 0.0673, 0.2350, 0.3541]])
torch.Size([2, 8])


In [55]:
import numpy as np

In [59]:
a = torch.ones(5)
b = a.numpy()
print(b)
type(b)

[1. 1. 1. 1. 1.]


numpy.ndarray

In [64]:
a.add_(1)
b *= 2
a

array([30., 30., 30., 30., 30.], dtype=float32)

In [66]:
b

array([30., 30., 30., 30., 30.], dtype=float32)

In [69]:
c = torch.from_numpy(b)
a

tensor([30., 30., 30., 30., 30.])

In [72]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z.numpy()