In [1]:
import torch

In [33]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.2632, -0.2185,  0.6242], requires_grad=True)


In [34]:
y = x + 2
print(y)

tensor([2.2632, 1.7815, 2.6242], grad_fn=<AddBackward0>)


In [35]:
 z = y * y * 2
print(z)

tensor([10.2442,  6.3477, 13.7730], grad_fn=<MulBackward0>)


In [36]:
z = z.mean()
print(z)

tensor(10.1216, grad_fn=<MeanBackward0>)


In [37]:
#v = torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
#z.backward(v) #dz/dx
z.backward()
print(x.grad)

tensor([3.0176, 2.3754, 3.4989])


In [39]:
print(x)
x.requires_grad_(False)
print(x)
x.requires_grad_(True)

tensor([ 0.2632, -0.2185,  0.6242], requires_grad=True)
tensor([ 0.2632, -0.2185,  0.6242])


In [44]:
weights = torch.ones(4,requires_grad=True)

for epoch in range(3):
    print("Epoch ",epoch)
    print("\tweights = ",weights)
    model_output = (weights* 3).sum() #Forward pass
    print("\tmodel output = ",model_output)
    model_output.backward() #Derivation
    print("\tgrads = ", weights.grad)
    weights.grad.zero_() #Empty out gradients to avoid accumilation

Epoch  0
	weights =  tensor([1., 1., 1., 1.], requires_grad=True)
	model output =  tensor(12., grad_fn=<SumBackward0>)
	grads =  tensor([3., 3., 3., 3.])
Epoch  1
	weights =  tensor([1., 1., 1., 1.], requires_grad=True)
	model output =  tensor(12., grad_fn=<SumBackward0>)
	grads =  tensor([3., 3., 3., 3.])
Epoch  2
	weights =  tensor([1., 1., 1., 1.], requires_grad=True)
	model output =  tensor(12., grad_fn=<SumBackward0>)
	grads =  tensor([3., 3., 3., 3.])


In [46]:
# optimizer = torch.optim.SGD(weights,lr=0.01)
# optimizer.step()
# optimizer.zero_grad()